import Head from 'next/head'
import { PostCard, Categories, PostWidget, } from '../components/index'
import { FeaturedPosts } from '../sections';
import { getPosts } from '../services/index'

export default function Home({ posts }) {
  return (
    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>
          BlogSpot
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts title="Featured Post" />
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {
            posts.map((post) => <PostCard post={post.node} key={post.title} />)
          }
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget slug={posts.slug} />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  )
}


export async function getStaticProps() {
  const posts = await getPosts() || [];
  return {
    props: {
      posts
    }
  }
}